// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logger.proto

package logger

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Severity int32

const (
	Severity_TRACE Severity = 0
	Severity_DEBUG Severity = 1
	Severity_INFO  Severity = 2
	Severity_WARN  Severity = 3
	Severity_ERROR Severity = 4
	Severity_FATAL Severity = 5
)

var Severity_name = map[int32]string{
	0: "TRACE",
	1: "DEBUG",
	2: "INFO",
	3: "WARN",
	4: "ERROR",
	5: "FATAL",
}

var Severity_value = map[string]int32{
	"TRACE": 0,
	"DEBUG": 1,
	"INFO":  2,
	"WARN":  3,
	"ERROR": 4,
	"FATAL": 5,
}

func (x Severity) String() string {
	return proto.EnumName(Severity_name, int32(x))
}

func (Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{0}
}

type ClientId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientId) Reset()         { *m = ClientId{} }
func (m *ClientId) String() string { return proto.CompactTextString(m) }
func (*ClientId) ProtoMessage()    {}
func (*ClientId) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{0}
}

func (m *ClientId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientId.Unmarshal(m, b)
}
func (m *ClientId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientId.Marshal(b, m, deterministic)
}
func (m *ClientId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientId.Merge(m, src)
}
func (m *ClientId) XXX_Size() int {
	return xxx_messageInfo_ClientId.Size(m)
}
func (m *ClientId) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientId.DiscardUnknown(m)
}

var xxx_messageInfo_ClientId proto.InternalMessageInfo

func (m *ClientId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Log struct {
	Severity             Severity             `protobuf:"varint,1,opt,name=severity,proto3,enum=logger.Severity" json:"severity,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Id                   string               `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	LogMessage           string               `protobuf:"bytes,4,opt,name=log_message,json=logMessage,proto3" json:"log_message,omitempty"`
	Tags                 map[string]string    `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{1}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetSeverity() Severity {
	if m != nil {
		return m.Severity
	}
	return Severity_TRACE
}

func (m *Log) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *Log) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Log) GetLogMessage() string {
	if m != nil {
		return m.LogMessage
	}
	return ""
}

func (m *Log) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Config struct {
	ServiceAddr          string   `protobuf:"bytes,1,opt,name=service_addr,json=serviceAddr,proto3" json:"service_addr,omitempty"`
	Tags                 []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{2}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetServiceAddr() string {
	if m != nil {
		return m.ServiceAddr
	}
	return ""
}

func (m *Config) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterEnum("logger.Severity", Severity_name, Severity_value)
	proto.RegisterType((*ClientId)(nil), "logger.ClientId")
	proto.RegisterType((*Log)(nil), "logger.Log")
	proto.RegisterMapType((map[string]string)(nil), "logger.Log.TagsEntry")
	proto.RegisterType((*Config)(nil), "logger.Config")
}

func init() {
	proto.RegisterFile("logger.proto", fileDescriptor_d43b7bfc6b6f7b16)
}

var fileDescriptor_d43b7bfc6b6f7b16 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x6d, 0x26, 0x6d, 0x6d, 0x6e, 0x96, 0x32, 0x5c, 0x54, 0x4a, 0x7c, 0xd8, 0x9a, 0xa7, 0xba,
	0x48, 0x2a, 0xf5, 0x41, 0xf1, 0x45, 0x62, 0xcd, 0xca, 0x4a, 0xdc, 0x85, 0xb1, 0xe2, 0xe3, 0x92,
	0x75, 0x66, 0x87, 0x61, 0xd3, 0x4e, 0xc9, 0xcc, 0x16, 0xfa, 0xdf, 0x7e, 0x80, 0x24, 0x33, 0x29,
	0xa2, 0x6f, 0xe7, 0x9e, 0x73, 0xc2, 0x39, 0x77, 0x6e, 0xe0, 0xac, 0xd6, 0x52, 0x8a, 0x26, 0xdb,
	0x37, 0xda, 0x6a, 0x1c, 0xbb, 0x29, 0x79, 0x21, 0xb5, 0x96, 0xb5, 0x58, 0x76, 0xec, 0xdd, 0xe3,
	0xfd, 0x52, 0x6c, 0xf7, 0xf6, 0xe8, 0x4c, 0xc9, 0xf9, 0xbf, 0xa2, 0x55, 0x5b, 0x61, 0x6c, 0xb5,
	0xdd, 0x3b, 0x43, 0x9a, 0xc0, 0x64, 0x5d, 0x2b, 0xb1, 0xb3, 0x57, 0x1c, 0xa7, 0x40, 0x14, 0x9f,
	0x05, 0xf3, 0x60, 0x11, 0x31, 0xa2, 0x78, 0xfa, 0x3b, 0x80, 0xb0, 0xd4, 0x12, 0x5f, 0xc3, 0xc4,
	0x88, 0x83, 0x68, 0x94, 0x3d, 0x76, 0xea, 0x74, 0x45, 0x33, 0x5f, 0xe5, 0xbb, 0xe7, 0xd9, 0xc9,
	0x81, 0x17, 0x40, 0xac, 0x99, 0x91, 0x79, 0xb0, 0x88, 0x57, 0x49, 0xe6, 0xf2, 0xb3, 0x3e, 0x3f,
	0xdb, 0xf4, 0xf9, 0x8c, 0x58, 0xe3, 0x13, 0xc3, 0x3e, 0x11, 0xcf, 0x21, 0xae, 0xb5, 0xbc, 0xdd,
	0x0a, 0x63, 0x2a, 0x29, 0x66, 0xc3, 0x4e, 0x80, 0x5a, 0xcb, 0x6f, 0x8e, 0xc1, 0x57, 0x30, 0xb4,
	0x95, 0x34, 0xb3, 0xd1, 0x3c, 0x5c, 0xc4, 0xab, 0x67, 0x7d, 0x8d, 0x52, 0xcb, 0x6c, 0x53, 0x49,
	0x53, 0xec, 0x6c, 0x73, 0x64, 0x9d, 0x25, 0x79, 0x07, 0xd1, 0x89, 0x42, 0x0a, 0xe1, 0x83, 0x38,
	0xfa, 0xdd, 0x5a, 0x88, 0x4f, 0x61, 0x74, 0xa8, 0xea, 0x47, 0xd1, 0x35, 0x8d, 0x98, 0x1b, 0x3e,
	0x90, 0xf7, 0x41, 0xfa, 0x11, 0xc6, 0x6b, 0xbd, 0xbb, 0x57, 0x12, 0x5f, 0xc2, 0x99, 0x11, 0xcd,
	0x41, 0xfd, 0x12, 0xb7, 0x15, 0xe7, 0x8d, 0xff, 0x3c, 0xf6, 0x5c, 0xce, 0x79, 0x83, 0xe8, 0x0b,
	0x91, 0x79, 0xb8, 0x88, 0x5c, 0xf2, 0xc5, 0x57, 0x98, 0xf4, 0xef, 0x82, 0x11, 0x8c, 0x36, 0x2c,
	0x5f, 0x17, 0x74, 0xd0, 0xc2, 0xcf, 0xc5, 0xa7, 0x1f, 0x5f, 0x68, 0x80, 0x13, 0x18, 0x5e, 0x5d,
	0x5f, 0xde, 0x50, 0xd2, 0xa2, 0x9f, 0x39, 0xbb, 0xa6, 0x61, 0x2b, 0x17, 0x8c, 0xdd, 0x30, 0x3a,
	0x6c, 0xe1, 0x65, 0xbe, 0xc9, 0x4b, 0x3a, 0x5a, 0x3d, 0xc0, 0xb8, 0xec, 0x76, 0xc4, 0x25, 0x44,
	0x39, 0xe7, 0x7e, 0x98, 0xf6, 0x9b, 0xbb, 0xa6, 0xc9, 0xe9, 0x20, 0xfd, 0x31, 0xd3, 0x01, 0xbe,
	0x81, 0x27, 0xa5, 0x96, 0xa5, 0xda, 0x09, 0x8c, 0xff, 0x7a, 0xa8, 0xe4, 0xf9, 0x7f, 0x47, 0x29,
	0xda, 0x3f, 0x26, 0x1d, 0xdc, 0x8d, 0x3b, 0xe6, 0xed, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18,
	0x30, 0x87, 0x7a, 0x69, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	AddLogger(ctx context.Context, in *Config, opts ...grpc.CallOption) (*ClientId, error)
	LogLine(ctx context.Context, in *Log, opts ...grpc.CallOption) (*empty.Empty, error)
}

type loggerClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggerClient(cc grpc.ClientConnInterface) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) AddLogger(ctx context.Context, in *Config, opts ...grpc.CallOption) (*ClientId, error) {
	out := new(ClientId)
	err := c.cc.Invoke(ctx, "/logger.Logger/AddLogger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) LogLine(ctx context.Context, in *Log, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/logger.Logger/LogLine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	AddLogger(context.Context, *Config) (*ClientId, error)
	LogLine(context.Context, *Log) (*empty.Empty, error)
}

// UnimplementedLoggerServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServer struct {
}

func (*UnimplementedLoggerServer) AddLogger(ctx context.Context, req *Config) (*ClientId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLogger not implemented")
}
func (*UnimplementedLoggerServer) LogLine(ctx context.Context, req *Log) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogLine not implemented")
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_AddLogger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Config)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).AddLogger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logger.Logger/AddLogger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).AddLogger(ctx, req.(*Config))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_LogLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LogLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logger.Logger/LogLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LogLine(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logger.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLogger",
			Handler:    _Logger_AddLogger_Handler,
		},
		{
			MethodName: "LogLine",
			Handler:    _Logger_LogLine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logger.proto",
}
